name: Deploy Dropbox Windows

on:
  push:
    branches:
      - master
    tags:
      - "!*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Build Release
      run: |
        msbuild ConsoleApplication1.sln -m /t:Build /p:Platform="x86" /p:Configuration=Release
